export const URL_BASE = 'http://localhost:4000/api'
// export const URL_BASE = 'https://fixadvisor-backend.up.railway.app/api'
export const URL_NEW_CLIENT = `${URL_BASE}/clients/new-client`
export const URL_CLIENTS = `${URL_BASE}/clients`
export const URL_FAVOURITES = `${URL_BASE}/favourites`
export const URL_NEW_PROVIDER = `${URL_BASE}/providers/new-provider`
export const URL_UPDATE_PROVIDER = `${URL_BASE}/providers/update-provider`
export const URL_PROVIDERS = `${URL_BASE}/providers`
export const URL_SERVICES = `${URL_BASE}/services`
export const URL_SERVICES_PROVIDER = `${URL_BASE}/services/provider`
export const URL_NEW_SERVICE = `${URL_BASE}/services/new-service`
export const URL_SEARCH_SERVICE = `${URL_BASE}/services/search`
export const URL_USERS = `${URL_BASE}/users`
export const URL_REVIEWS_SERVICE = `${URL_BASE}/reviews`
export const URL_NEW_REVIEW_SERVICE = `${URL_BASE}/reviews/newReview`
